import React from 'react'

const About = (props) => {
  return (
    <>
    <div className={`container p-2 bg-${props.theme} `} >
        <div className="accordion " id="accordionExample" >
            <h1 className={`text-${props.theme==='light'?'dark':'light'}`}>About Text Utils</h1>
            <div className="accordion-item">
                <h2 className="accordion-header" id="headingOne">
                    <button className={`accordion-button bg-${props.theme} text-${props.theme==='light'?'dark':'light'}`} type="button"  data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Accordion Item #1
                    </button>
                </h2>
                <div id="collapseOne" className={`accordion-collapse collapse show bg-${props.theme}  text-${props.theme==='light'?'dark':'light'}`} aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                    <div className={`accordion-body `}>
                        <strong>This is the first item's accordion body.</strong> Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni similique consectetur nam perspiciatis ad vel minima inventore commodi error praesentium, voluptatum iste harum sunt reprehenderit. Excepturi consectetur suscipit reiciendis quia!
                        Mollitia reprehenderit optio libero, vitae minus fugit exercitationem nobis officiis! Velit eaque, perspiciatis impedit nihil iste pariatur exercitationem cumque aliquid, laboriosam facilis, eligendi voluptates ducimus! Sint, corporis omnis. Adipisci, accusantium.
                        Non, suscipit nesciunt! Saepe perspiciatis accusantium odio, esse doloribus ratione fugit? Aspernatur harum adipisci qui doloribus accusamus quo. Qui quod sequi nam voluptas minus reiciendis similique adipisci officia illo culpa.
                        Exercitationem vitae, inventore eos laborum enim molestiae facere, nemo, perferendis dignissimos animi iusto. Quas reprehenderit magnam consectetur magni alias, illum minus ab quia aperiam sapiente vero assumenda inventore nulla ad.
                        Ex adipisci iure eligendi eos necessitatibus. Magnam amet velit ullam porro sint expedita repellat labore inventore illum aspernatur, nam iste reprehenderit ab laudantium voluptas harum ipsam hic mollitia impedit maxime!
                        In, corrupti. Dolorem vitae doloremque exercitationem labore ipsum non, nihil deserunt, earum mollitia, natus est repudiandae necessitatibus rem adipisci harum ex molestiae! Corrupti quo praesentium voluptate illum nobis nihil deserunt?
                        Ratione, animi eligendi consectetur error esse accusantium harum necessitatibus, odit cumque dolor saepe iure odio facilis tenetur aliquid repudiandae quae in alias ipsam neque, similique cupiditate tempore libero nobis? Illum?
                        Assumenda numquam deserunt reprehenderit accusantium iure dignissimos pariatur voluptas optio rem soluta id quo maxime fuga voluptate, quam obcaecati expedita itaque voluptatibus deleniti impedit aliquid dolorum odit quas. Tenetur, consectetur?
                        Blanditiis sapiente dolor qui, veniam corporis aliquam assumenda ratione voluptatibus aperiam esse. Sint labore unde, molestiae corrupti saepe cupiditate, expedita totam maxime amet ea iste incidunt, magnam odio nam voluptatum.
                        Velit ipsa itaque unde aspernatur, commodi excepturi laboriosam neque in fugiat quo quaerat tempora modi. Ea perspiciatis nam commodi pariatur, repellat dolorum eveniet quia provident aut tempore consequatur, odit ipsa.
                        Libero quisquam cum eveniet perspiciatis at animi iusto nihil sed? Neque fuga magnam sapiente quia debitis perspiciatis accusamus quidem incidunt quisquam obcaecati sequi at rerum in ipsa quaerat, eaque ut.
                        Sequi tempore provident sapiente unde ipsam nemo ratione, reprehenderit asperiores laborum odio consequatur soluta commodi nostrum deserunt possimus consequuntur quidem. Aperiam, odit commodi! Non accusantium magnam voluptate, reiciendis aut culpa?
                        Eveniet libero, officiis dolorem molestias impedit necessitatibus? Dicta iusto voluptas magnam ducimus facilis eum ea dignissimos odio nesciunt sed sunt et recusandae, aspernatur quidem deserunt. Voluptate aliquam debitis eos provident?
                        Explicabo accusantium voluptate nemo labore quis omnis hic deserunt, natus nesciunt aspernatur soluta quo animi harum tempora mollitia dignissimos? Temporibus beatae magnam consequatur sed ab minus, nobis eius esse enim?
                        Consequatur fuga similique dolorem tempore magni, necessitatibus fugit voluptates! Veniam temporibus dolores accusamus laborum quae. Delectus enim labore atque hic voluptatem soluta ea magni quibusdam, quo laboriosam, magnam provident. Tenetur.
                        Fugit corporis obcaecati expedita sunt, incidunt dolorem labore doloremque in voluptate nobis accusamus suscipit, aut quo facilis voluptatem, quia rem ad porro optio reprehenderit maiores iure maxime quod corrupti. Provident?
                        Perspiciatis non neque voluptatibus odio dolore molestiae molestias est minima, exercitationem tenetur accusamus maiores, ipsum accusantium officia praesentium facilis deserunt culpa! Veritatis tempore eveniet corporis, ea cumque excepturi doloribus reiciendis!
                        Adipisci cumque modi at soluta atque aliquam nemo iusto. Repellat maxime quidem autem in magnam, earum illo consectetur nulla saepe. Quidem beatae animi voluptate quis omnis, molestias repellat fugiat aspernatur!
                        Corrupti, molestiae illum error velit possimus iure, ullam fugiat dignissimos fugit, deleniti aperiam. Omnis sapiente odit deleniti harum est consequuntur recusandae hic inventore. Ex quae reiciendis ullam nemo dolorem in?
                        Vitae nulla quos reprehenderit architecto quidem in facilis quaerat fuga recusandae beatae! Soluta veniam, minima assumenda aperiam rem delectus perspiciatis et officiis aspernatur, mollitia doloremque omnis voluptatibus, amet quibusdam! Maxime.
                        Explicabo totam animi magni, quas a fugit quae at sed, ipsa soluta ipsam quisquam debitis excepturi adipisci optio pariatur et voluptas sequi repellat aliquid iure esse cumque molestias. Velit, ullam?
                        Tempora accusantium pariatur fugiat praesentium voluptatum amet, unde vel at, optio cum laudantium dolorem blanditiis minus assumenda, quasi omnis sunt ipsam qui nostrum doloremque? Autem beatae praesentium vitae nam sint.
                        Omnis fuga aspernatur, architecto sint possimus tempora, nam atque fugiat accusamus perspiciatis quibusdam suscipit totam esse, voluptatibus animi. Cumque, dicta velit. Ipsum nam hic a reiciendis aliquam, quia at quidem.
                        Deleniti voluptatum fuga voluptas sunt suscipit eos. Fugit at officiis ut obcaecati, sit numquam placeat vitae commodi, id sunt harum quas necessitatibus dicta eligendi minima soluta aspernatur aliquam amet? Deleniti.
                        Possimus labore ab velit, nobis at maxime, quam quae eius inventore, odit et. Eius obcaecati debitis enim, natus quae cupiditate eos mollitia soluta animi. Tenetur adipisci dignissimos quidem provident enim?
                        Expedita fugit voluptas nostrum non inventore odit, reiciendis odio quia debitis quod consequatur ad dicta corrupti maxime consequuntur cumque itaque illo? Tempora cumque vitae voluptatum minima facere, maxime cum corrupti?
                        Impedit, perferendis consequatur laboriosam provident fuga architecto autem corporis aspernatur nemo incidunt voluptatum iure modi ipsa vero ipsum eaque aperiam quasi quae corrupti consectetur. Aliquam enim quam at ipsa illo.
                        Ipsam distinctio obcaecati at fugiat libero inventore amet quidem laudantium eaque explicabo soluta officia neque eos odio suscipit tempora optio odit, voluptatem expedita sunt! Eum quas culpa esse error perferendis?
                        Nisi cumque eius suscipit itaque expedita. Facilis officia molestiae eum assumenda dolorem adipisci, harum consequatur iste illum reiciendis dolores quam, fugit voluptates distinctio ducimus itaque! Itaque nostrum maiores voluptatum natus.
                        Maiores harum consequuntur, voluptate sapiente et molestias ut! Velit architecto numquam et. Impedit dolor aut laboriosam voluptates quas illum corrupti, tempore qui, praesentium nesciunt in, incidunt unde quaerat eaque facere!
                        Adipisci in aperiam reiciendis minus minima, asperiores quos! Ipsam molestiae, beatae id corporis temporibus dolore ducimus minus est eius debitis aliquam tenetur! Mollitia omnis ut quibusdam aut obcaecati corporis non!
                        Blanditiis ratione atque exercitationem consectetur eveniet minus, ipsum explicabo doloribus vero rerum, quibusdam dolor autem a maxime commodi maiores quaerat eius. Sequi, provident dignissimos. Illum numquam eius vitae aliquid odio!
                        Tempora quaerat quod, eveniet ducimus suscipit ab odio rem id fugit! Voluptates eligendi inventore, voluptatem alias, deserunt consequatur vero similique rerum fugiat facilis incidunt! Magni fugit soluta quam nesciunt rerum.
                        Error sed blanditiis quia, possimus a iure eos ut quaerat, cumque eveniet quisquam perspiciatis eligendi molestias praesentium at totam obcaecati ab. Dicta incidunt sit laboriosam reprehenderit aspernatur neque alias repellendus.
                        Ut ad repellat, doloribus consequuntur voluptate reiciendis officiis dolorem quisquam nulla incidunt quas perferendis debitis ratione, suscipit libero! Voluptas aliquam fugiat animi doloremque, enim amet ab dolore explicabo deleniti distinctio?
                        In, repellat atque. Velit, laboriosam, dignissimos asperiores quis rem dolore magnam blanditiis magni praesentium vitae quod eius sint deserunt perferendis iste dolor tempora. Ullam esse fuga repellendus. Cum, saepe iste!
                        Voluptatum similique consequatur maxime nihil aliquid voluptatibus provident possimus error tempore ipsam. Illo quaerat expedita totam praesentium aspernatur molestiae dolores ullam. Quod repellendus hic cumque incidunt reprehenderit, pariatur vero dolorum.
                        Temporibus, aliquid quis cumque laborum labore consectetur nulla dolores harum ipsum at repellendus. Molestias quo enim blanditiis. Nam obcaecati exercitationem totam dolores corporis. At et dolores sed necessitatibus eos exercitationem?
                        Recusandae totam atque officiis, ab laudantium deleniti, debitis sit, tenetur qui repudiandae distinctio vel numquam maxime excepturi minima nisi rerum. Similique, aliquam culpa laborum laudantium nesciunt quae optio reiciendis error.
                        Similique voluptatum perferendis ad explicabo eius amet aut ea culpa pariatur odit totam vel cum fuga, ducimus voluptates expedita nisi ratione est incidunt, reprehenderit veritatis, quibusdam repellat alias! Repellat, libero?
                        Tenetur quia accusantium quis quas, nesciunt magnam temporibus ab soluta numquam dicta in. Est distinctio hic, dolorem aliquid dolores debitis ipsa architecto obcaecati cupiditate rerum fugit? Praesentium tempora distinctio possimus?
                        Maxime molestiae commodi incidunt nemo ex consectetur numquam cumque ipsa? Ratione quas quaerat nemo facilis amet fuga distinctio. Qui nisi iste quidem. Deleniti vitae fuga tenetur est sapiente totam architecto?
                        Vero esse doloremque numquam, ab laudantium beatae fugiat error eaque voluptatum. Dicta deleniti saepe molestiae consequuntur beatae. Odit, aut dignissimos a dolor quasi reiciendis labore modi molestiae omnis, nemo soluta.
                        Magni, nisi est ab laudantium hic similique nemo. Ex perspiciatis odio, vero asperiores quia repudiandae at magni necessitatibus error reprehenderit explicabo qui, voluptates repellat. Id nulla illo quis ad minima?
                        Modi doloribus suscipit, necessitatibus optio animi expedita cumque, quae non est fuga vitae perferendis accusamus. Dolore voluptates, est exercitationem quo recusandae quisquam nihil eligendi culpa deleniti provident, aliquam qui asperiores.
                        Totam, veniam nostrum dicta illum eius, ut animi accusamus, nobis repellendus doloribus qui cum. Eius, ullam sunt! Quos temporibus, eligendi cumque iure distinctio pariatur laudantium velit dolorem esse fuga eius.
                        Adipisci quo error quisquam nam quas atque voluptate incidunt eos nisi, expedita maxime ipsam architecto autem aperiam porro eveniet numquam aspernatur repellat. At aperiam aliquid dicta corrupti quia inventore cum.
                        Veritatis, velit dicta corrupti facilis eligendi deserunt, labore quas fuga quod officiis ratione accusantium voluptate rem nobis at modi dolore neque eum deleniti fugiat ipsam odit aliquam. Assumenda, nobis ipsum.
                        Illo odio ullam fugiat ratione pariatur, architecto magnam odit, reprehenderit eligendi ipsam, repellendus suscipit delectus illum. Autem sapiente nihil iste, voluptatem architecto aliquid odit eos voluptatum similique deleniti dolore facilis!
                        Illum repellat adipisci harum quasi est, explicabo quibusdam itaque a veniam cumque dicta eos! Blanditiis eius iusto amet at recusandae eum suscipit repellat, rerum obcaecati, nisi error, eveniet ipsum neque.
                        Dolorem nisi obcaecati inventore vitae perspiciatis expedita delectus repellat in consequuntur voluptatibus quo provident, nihil aperiam! Soluta eius inventore quos dolores, dignissimos, itaque, veritatis ratione suscipit assumenda minus tempore dolorem.
                        Adipisci officiis debitis iure, quas corrupti libero omnis veniam hic! Provident ea iste earum, eaque nesciunt, id illum placeat error in exercitationem iusto quibusdam soluta! Dignissimos ipsam perferendis soluta harum.
                        Aspernatur velit ipsam sint, consectetur dicta quae cum, culpa modi assumenda amet, nobis tempore similique repellat deleniti. Eum, iusto nostrum consequatur molestias odio excepturi tempora atque porro architecto corrupti? Molestias.
                        Earum facere, labore dolore corrupti tempore sit dolores aut laboriosam magnam provident animi consequatur optio dolorem rerum rem error quis eveniet culpa. Dolore nihil voluptas error perspiciatis! Architecto, omnis earum.
                        Quia dolorem ad enim, provident, sunt accusantium rem, odit iste esse voluptate ex placeat fugiat error eveniet vero! Voluptates aperiam id dolorum atque vel sequi quos maxime error dolore est!
                        Perferendis veniam suscipit ad quisquam ipsum. Deleniti sit in ipsa eveniet ad, quidem corporis, maxime accusantium quo ducimus cum? Natus incidunt laboriosam repellat molestias, sapiente eius adipisci distinctio unde magnam!
                        Dolorum quisquam facere veniam commodi ullam perspiciatis corporis suscipit aut cum quas deleniti nemo neque laborum, sapiente laudantium perferendis rerum obcaecati quis sunt similique? Et explicabo molestias magni velit eveniet!
                        Fuga ducimus eos animi accusantium laboriosam unde necessitatibus dignissimos assumenda possimus autem dolorem neque inventore voluptatem quia, architecto sed voluptate obcaecati repudiandae veniam non consectetur vitae hic odio? Nihil, consequuntur!
                        Debitis dolor laborum, perferendis, itaque officia tenetur neque cum vitae excepturi minima reiciendis labore optio? Rerum repellendus reiciendis facilis molestias numquam voluptatem eveniet sed ad, neque autem! Laudantium, porro debitis.
                        Similique nulla cum nam aperiam quas nisi aspernatur, facere inventore ipsa quia mollitia. Ullam eaque totam voluptatibus delectus sapiente soluta debitis odit? Temporibus corrupti odit magnam. Ipsam quis iure quae?
                        Ducimus similique aspernatur quasi obcaecati, fugit voluptatibus aut atque sit ullam dolores quo tenetur veritatis quas eum mollitia eaque molestiae quaerat doloribus. Quasi, officiis quo quisquam consectetur suscipit eveniet numquam.
                        Aut vel ducimus, quisquam dolores rem quae repellat, minus veniam nostrum totam explicabo veritatis vero unde, similique sequi asperiores error? Nulla molestiae numquam maiores iure omnis illo, odit explicabo quidem.
                        Voluptatem, aspernatur magnam accusamus provident cumque nobis expedita a. Libero sed deserunt voluptatem tenetur aut, illo quibusdam! Minima magni eaque consectetur placeat molestiae dignissimos, est porro nisi consequuntur iusto dolore?
                        Consequatur aliquid harum facilis libero ut sed odio laudantium repellendus eum, debitis soluta laboriosam perferendis voluptatum, dignissimos recusandae consectetur reprehenderit. Eligendi corrupti blanditiis eum laudantium deserunt qui pariatur laborum veniam?
                        Et, sed rem veniam minima dolor minus hic nihil eum quas. Perferendis, optio dolorum aspernatur illum maxime quas praesentium voluptatum sit harum impedit esse alias odit aut repudiandae incidunt mollitia!
                        Optio doloremque sint explicabo accusantium voluptatibus sunt, repudiandae eligendi atque consequatur molestias nisi fugit voluptas, excepturi ab. Natus ut porro itaque doloribus sapiente ex consequuntur fugiat, aperiam ratione repellendus reprehenderit?
                        Voluptates alias accusantium consequatur? Sunt cumque laudantium hic beatae eaque nostrum numquam voluptatum, quae provident ipsum alias. Repellendus, architecto laboriosam! Adipisci tenetur, deserunt delectus quos omnis recusandae quidem praesentium esse?
                        Voluptates suscipit adipisci, in repudiandae repellendus fuga. Consequatur nulla tempore nihil itaque quisquam labore, beatae nemo! Facere corrupti ratione maxime delectus aspernatur, rem exercitationem omnis nesciunt itaque dolorem aut quia.
                        Cumque fugit ipsa vitae iusto dolores quis asperiores, accusamus, tempore, deleniti iure voluptatem. Perferendis, debitis eum, exercitationem dolorum fugit natus laborum in cupiditate maxime ullam magnam dolor quod, illo deleniti.
                        Iusto voluptate incidunt nobis reiciendis. Labore nam mollitia pariatur libero, voluptate quidem, ullam laudantium repellat praesentium quibusdam quas nulla ad qui eligendi veritatis aperiam. Quas id eaque quaerat nesciunt dolorum.
                        Fuga neque ratione hic, alias veritatis quos provident sequi, sit excepturi quis minus aperiam blanditiis consequatur voluptas eum porro distinctio ea. Laboriosam ducimus cum officiis mollitia exercitationem aut, ea asperiores!
                        Ea blanditiis commodi distinctio neque, explicabo, porro aut odio atque dolorem repellat modi provident autem enim sit sapiente repellendus non, totam harum eum alias necessitatibus maiores. Odio fugit qui molestiae!
                        Deleniti quisquam laudantium voluptatum laboriosam veritatis magnam. Quia ex minus fugiat debitis voluptatum pariatur beatae necessitatibus porro facere nisi id sed, dolores accusantium unde at deleniti voluptatibus totam inventore corrupti.
                        Aliquam animi neque autem atque doloribus labore cumque incidunt quibusdam perspiciatis illum pariatur distinctio voluptatibus aut sapiente mollitia nostrum illo eveniet quod, dolor accusantium similique repudiandae tenetur expedita tempora! Vel?
                        Quas, quam consequatur. Eum aut reiciendis itaque! Facilis quasi doloremque, modi nisi pariatur doloribus ad ipsum quod illum vitae perferendis sequi nesciunt a dolorem. Quibusdam debitis beatae dolore tempora deserunt.
                        Dolores quo, voluptas at sunt nobis praesentium tenetur, cumque pariatur, iusto neque odit et alias doloremque minus. Pariatur ullam provident rem, accusamus voluptatum et ipsum, sint hic, ex esse quos.
                        Blanditiis fugiat impedit nostrum, nobis molestiae, magni quaerat recusandae dicta similique dolor mollitia repudiandae nam, ea ad non quam id vitae. Neque cum ab nam omnis? Magni alias similique quo?
                        Aspernatur corporis pariatur voluptate facilis ea dicta ratione perspiciatis, distinctio fugit exercitationem autem dolorem inventore alias ullam impedit reprehenderit totam similique in amet id dolorum! Veniam iusto delectus sunt necessitatibus!
                        Molestias reiciendis ipsum quos ratione esse praesentium soluta perspiciatis. Cupiditate eveniet necessitatibus tenetur aliquid totam ex enim laborum tempora, iure id ullam illo vitae praesentium eum odio ut cumque illum.
                        Deleniti reiciendis placeat officiis maiores magnam sapiente nisi, necessitatibus vitae dolorum itaque aperiam delectus atque repellendus quibusdam earum rem accusantium ut quasi! Exercitationem fugit corporis eligendi autem ut cum earum.
                        Consequuntur quis consectetur, amet doloremque illo minus ad? Alias, quod velit! Impedit dolores repellat perspiciatis ex facere nihil earum vitae eveniet, incidunt, eum eius voluptatum nobis omnis ipsum quod voluptatibus!
                        Ex esse omnis, quaerat consectetur nam, inventore amet praesentium atque voluptates officiis animi repellendus voluptatibus natus neque, repellat dolorum quis consequuntur aut facilis dolor sed. Quasi aliquid dolores accusamus quae?
                        Minima quasi ratione sunt iste, veniam aliquid rem sit reiciendis quis, quia exercitationem iusto, perferendis eos eius? Praesentium eius, perspiciatis a alias facere laudantium nostrum dolores sunt, voluptate quisquam sit?
                        Magnam perspiciatis ab harum similique molestias! Accusamus, quos laboriosam? Sit, veritatis dignissimos. Doloribus tempora a in, molestiae magnam omnis dolorem itaque adipisci error natus beatae hic ipsum ducimus incidunt sint?
                        Natus voluptatem praesentium velit optio iste consequatur delectus in animi saepe ipsum harum, quos repellat totam accusamus quibusdam sint similique iure nulla obcaecati rerum quis eligendi veniam tempore deserunt? Illum.
                        Expedita repudiandae minus recusandae sequi quae ex debitis exercitationem, nam ullam quibusdam aspernatur quos laudantium rerum. Tempora laudantium velit commodi adipisci, eligendi dolorem reiciendis harum nesciunt possimus quo. Minus, sed?
                        Fuga labore soluta quam laudantium in eum, unde fugiat molestias odio similique distinctio dolorem? Adipisci reprehenderit vitae ducimus quod ut consequuntur facere enim debitis. Placeat ipsam beatae dolor unde alias!
                        Architecto obcaecati quo quaerat ducimus facilis, totam hic temporibus fugit alias quos sit inventore quidem repellendus, tenetur quis dolorum natus libero asperiores minus laudantium dicta magnam excepturi voluptas possimus. Repudiandae?
                        Molestiae, minima velit est ea nisi quidem, recusandae aliquid tempora quam ex soluta consequuntur et hic saepe voluptatum natus veniam deserunt. Odit temporibus libero, sapiente qui soluta impedit aliquam necessitatibus.
                        Ex officia nemo at eum eaque. Exercitationem repellat minus, ipsam impedit in sapiente nemo rem, praesentium consectetur, quod voluptatum. Esse repellendus saepe tempore ipsa nulla dolorum veritatis, voluptatum aliquam impedit!, though the transition does limit overflow.
                    </div>
                </div>
            </div>
        </div>
        {/* <button className="btn btn-outline-primary mt-5" >Enable {props.theme} Theme</button> */}
    </div>
    </>
  )
}

export default About